version: '2'
services:
  barcws:
    container_name: barc-ws
    build: .
    volumes:
      - "./bin/www:/src/bin/www"
    ports:
      - "443:443"
    links:
      - "redis:redis"
    depends_on:
      - "redis"
    environment:
      - PORT=443
  
  redis:
    image: redis
    container_name: barc-redis
    ports:
      - "6379:6379" #publish redis to local host as well as link to barcws
